# Generated by Django 3.0.3 on 2020-08-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FirstName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LastName',
        ),
        migrations.AddField(
            model_name='contact',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
