# Generated by Django 3.0.3 on 2020-08-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_github_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
